# Generated by Django 5.0 on 2023-12-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='House', max_length=250, verbose_name='Title')),
                ('images', models.ImageField(height_field=300, upload_to='houses/', verbose_name='Images', width_field=300)),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('num_of_rooms', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Number of rooms')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Price')),
                ('space', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Space')),
                ('repair', models.BooleanField(verbose_name='Repaired')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
    ]
