# Generated by Django 5.0 on 2023-12-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housesmodel',
            name='images',
            field=models.ImageField(height_field='300px', upload_to='houses/', verbose_name='Images', width_field='300px'),
        ),
    ]
